"""empty message

Revision ID: 4029a66d5759
Revises: 6789d97625d4
Create Date: 2022-09-27 21:28:29.406191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4029a66d5759'
down_revision = '6789d97625d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('owm_current_weather', 'wind_direction_value_deg',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('owm_current_weather', 'wind_direction_value_deg',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
