"""empty message

Revision ID: 6b47e06d011f
Revises: eb72ec48b7f4
Create Date: 2022-09-27 22:38:44.038158

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6b47e06d011f'
down_revision = 'eb72ec48b7f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('owm_current_weather', 'wind_direction_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('owm_current_weather', 'wind_direction_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('owm_current_weather', 'lastupdate_value',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('owm_hourly_weather_forecast', 'wind_direction_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('owm_hourly_weather_forecast', 'wind_direction_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('owm_hourly_weather_forecast', 'wind_direction_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('owm_hourly_weather_forecast', 'wind_direction_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('owm_current_weather', 'lastupdate_value',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('owm_current_weather', 'wind_direction_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('owm_current_weather', 'wind_direction_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
