"""empty message

Revision ID: d561d91101de
Revises: 6b47e06d011f
Create Date: 2022-10-18 21:06:01.316327

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd561d91101de'
down_revision = '6b47e06d011f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('owm_current_weather', 'city_sun_rise',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('owm_current_weather', 'city_sun_set',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('owm_current_weather', 'wind_speed_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('owm_current_weather', 'cloud_value_pct',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('owm_current_weather', 'cloud_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('owm_current_weather', 'visibility_value_m',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('owm_current_weather', 'visibility_value_m',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('owm_current_weather', 'cloud_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('owm_current_weather', 'cloud_value_pct',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('owm_current_weather', 'wind_speed_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('owm_current_weather', 'city_sun_set',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('owm_current_weather', 'city_sun_rise',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
