"""empty message

Revision ID: eb72ec48b7f4
Revises: 4029a66d5759
Create Date: 2022-09-27 21:30:07.101816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb72ec48b7f4'
down_revision = '4029a66d5759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('owm_hourly_weather_forecast', 'wind_direction_value_deg',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('owm_hourly_weather_forecast', 'wind_direction_value_deg',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
